### ISSUE TITLE
Add support for Steam HD version

### ISSUE THREAD

**Issue by notsure8x** [notsure8x/e2140-unofficial-patch#7]
As in title, add support for Steam HD version.

**Comment by Pentix1985** [comment]
Is this implemented in the latest version? If not. Is it possible to release a Steam-enabled version? Like 1.1.1 :)

**Comment by notsure8x** [comment]
> Is this implemented in the latest version? If not. Is it possible to release a Steam-enabled version? Like 1.1.1 :)

Hi, it's not implemented (yet). Target version for steam HD support is 1.2, at least for AI issues.

In my sandbox, I ported most of the fixes for steam hd, but there are some additional issues in AI code which needs extra work comparing to GoG.

**Comment by notsure8x** [comment]
Adding this comment as progress update. I've finally managed to fix AI code in Steam version in my sandbox, also sound engine fixes were done, now working on windowed mode support, alt+f4 support etc as in GoG to have feature "parity" between GoG and Steam HD versions. All mentioned work is still done only in sandbox, after it's verified, I will create actual patch and patch installer.

**Comment by Pentix1985** [comment]
I'm watching you :)
